### PR TITLE
Loading syles TS sizing help

### PR DESCRIPTION
**Pull request by thompsongl**

### CODE REVIEW

**Comment by thompsongl** [comment]
Outdated branch. Will reopen

**Comment by thompsongl** [comment]
Nevermind. Looks like you got it figured out

**Comment by cchaos** [comment]
Hehe. I will ask though that there seems to be 2 possible methods. The way I created the array in the JS file first, or your option which is to create the `type` first in the styles file. Is there a clear better method here?

**Comment by thompsongl** [comment]
I'm not _aware_ of any technical benefit to the different approaches. I mostly see it as a style preference or readability decision.

**Comment by cchaos** [comment]
My original worry was that there'd be a circular dependency with the `styles.ts` file requiring a type in `component.js` while `component.js` imports the component them function from `styles.ts` but it doesn't seem to complain.

**Pull request closed without merging**
